version: "3.9"
services:
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     SA_PASSWORD: "YourStrong@Passw0rd"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: AP.CityDataDemo.Presentation/Dockerfile
    ports:
      - "5265:80"
    # depends_on:
    #   - sqlserver
    # environment:
    #   ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MyApp;User Id=sa;Password=YourStrong@Passw0rd;"

  web:
    build:
      context: .
      dockerfile: AP.CityDataDemo.BlazorApp/Dockerfile
    ports:
      - "5240:80"
    depends_on:
      - api
# volumes:
#   sql_data:
